In [0]:
!pip install tensorflow==2.0

In [0]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 15659149963640423028, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 17641191329823782341
 physical_device_desc: "device: XLA_CPU device"]

In [0]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### upload csv file

In [0]:
#from google.colab import files
#uploaded = files.upload()

In [0]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### Preprocessing

In [0]:
dataset = pd.read_csv('Customer_Churn_Modelling.csv')

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.drop(labels=['RowNumber', 'Surname', 'CustomerId', 'Exited'], axis=1)
y = dataset['Exited']

In [0]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [0]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()

In [0]:
X['Geography'] = l1.fit_transform(X['Geography']) 

In [0]:
X.head(2)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58

[2 rows x 10 columns]

In [0]:
X['Gender'] = l1.fit_transform(X['Gender'])

In [0]:
X.head(2)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58

[2 rows x 10 columns]

In [0]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

### Feature Standardization

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
X_test

array([[-1.975956  , -1.09665089,  0.1093321 , ..., -0.15254674,
         1.72974448, -0.57504086],
       [ 0.64576103, -1.09665089, -1.42330499, ...,  0.36818473,
         1.72974448, -0.57504086],
       [ 0.12763513,  0.91186722,  2.40828774, ..., -1.46485588,
        -0.57812007,  1.73900686],
       ...,
       [-1.20912968,  0.91186722,  0.20512192, ..., -1.49962429,
        -0.57812007, -0.57504086],
       [ 1.10171182, -1.09665089,  1.54617938, ..., -0.10699919,
        -0.57812007,  1.73900686],
       [ 0.9773616 , -1.09665089, -0.75277626, ...,  0.69518685,
        -0.57812007,  1.73900686]])

In [0]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

### Build ANN

In [0]:
X.shape, X_train.shape

((10000, 11), (8000, 11))

In [0]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim=X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [0]:
X.shape[1]

11

In [0]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(X_train, y_train.to_numpy(), batch_size=10, epochs=10, verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 2s 195us/sample - loss: 0.3285 - accuracy: 0.8636
Epoch 2/10
8000/8000 [==============================] - 2s 193us/sample - loss: 0.3263 - accuracy: 0.8645
Epoch 3/10
8000/8000 [==============================] - 2s 195us/sample - loss: 0.3259 - accuracy: 0.8643
Epoch 4/10
8000/8000 [==============================] - 2s 196us/sample - loss: 0.3234 - accuracy: 0.8641
Epoch 5/10
8000/8000 [==============================] - 2s 201us/sample - loss: 0.3226 - accuracy: 0.8662
Epoch 6/10
8000/8000 [==============================] - 2s 196us/sample - loss: 0.3223 - accuracy: 0.8664
Epoch 7/10
8000/8000 [==============================] - 2s 197us/sample - loss: 0.3212 - accuracy: 0.8680
Epoch 8/10
8000/8000 [==============================] - 2s 192us/sample - loss: 0.3207 - accuracy: 0.8685
Epoch 9/10
8000/8000 [==============================] - 2s 195us/sample - loss: 0.3198 - accuracy: 0.8685
Epoch 10/10
8000/8000 [=

In [0]:
y_prd = model.predict_classes(X_test)

In [0]:
y_prd

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [0]:
model.evaluate(X_test, y_test.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.3521705675125122, 0.858]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
confusion_matrix(y_test, y_prd)

array([[1553,   40],
       [ 244,  163]])

In [0]:
accuracy_score(y_test, y_prd)

0.858